apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

- patches:
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: minio

- patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: minio-service
- patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: minio-pvc
- patches:
  - patch: |-
      $patch: delete  
      kind: ConfigMap
      metadata:
        name: pipeline-install-config        


