apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
#patchesStrategicMerge:
#- delete-minio.yaml
generatorOptions:
  # mlpipeline-minio-artifact needs to be referred by exact name
  disableNameSuffixHash: true
configMapGenerator:
- name: pipeline-install-config
  env: pipeline-install-config.env
  #behavior: merge
  namespace: kubeflow  
- name: workflow-controller-configmap
  files:
  - config
  namespace: kubeflow    
- name: ml-pipeline-ui-configmap
  files:
  - viewer-pod-template.json
  namespace: kubeflow 
- name: kubeflow-pipelines-profile-controller-code
  files:
  - sync.py
  namespace: kubeflow 
secretGenerator:
- name: mlpipeline-minio-artifact
  env: object-store-secrets.env
  namespace: kubeflow 
# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines
vars:
- name: kfp-artifact-storage-endpoint
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.objStoreHost
- name: kfp-artifact-storage-insecure
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.insecure