apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
generatorOptions:
  # mlpipeline-minio-artifact needs to be referred by exact name
  disableNameSuffixHash: true
configMapGenerator:
- name: pipeline-install-config
  env: pipeline-install-config.env
  behavior: merge
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config
- name: ml-pipeline-ui-configmap
  behavior: replace
  files:
  - viewer-pod-template.json
- name: kubeflow-pipelines-profile-controller-code
  behavior: replace
  files:
  - sync.py
secretGenerator:
- name: mlpipeline-minio-artifact
  env: object-store-secrets.env
  behavior: replace
patchesStrategicMerge:
- ntnx-config-patch.yaml
- delete-minio.yaml
# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines
vars:
- name: kfp-artifact-storage-endpoint
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.objStoreHost
- name: kfp-artifact-storage-insecure
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.insecure