---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kubeflow-instance
  namespace: ${releaseNamespace}
spec:
  interval: 1m0s
  ref:
    tag: v1.8.1
  timeout: 15m0s
  url: https://github.com/kubeflow/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-instance
  namespace: ${releaseNamespace}
spec:
  wait: true
  patches:
  - patch: |
      $patch: delete 
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: minio
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: minio-service
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: minio-pvc  
  - patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: istio-ingressgateway
      namespace: istio-system
  - patch: |
     - op: add
       path: /metadata/namespace
       value: default
    target:
      kind: ConfigMap
      name: default-install-config.*
  - patch: | 
      apiVersion: networking.istio.io/v1beta1
      kind: Gateway
      metadata:
        name: kubeflow-gateway
      spec:
        servers:
        - hosts:
          - '*'
          port:
            name: http
            number: 80
            protocol: HTTP        
        - hosts:
          - '*'
          port:
            name: https
            number: 443
            protocol: HTTPS
          tls:
            credentialName: kubeflow-tls
            mode: SIMPLE
    target:
      kind: Gateway
      name: kubeflow-gateway
      namespace: kubeflow
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ml-pipeline-ui
      spec:
        template:
          spec:
            containers:
              - name: ml-pipeline-ui
                env:
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: mlpipeline-minio-artifact
                        key: accesskey
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: mlpipeline-minio-artifact
                        key: secretkey
                  - name: AWS_S3_ENDPOINT
                    valueFrom:
                      configMapKeyRef:
                        name: pipeline-install-config
                        key: objStoreHost
                  - name: AWS_REGION
                    valueFrom:
                      configMapKeyRef:
                        name: pipeline-install-config
                        key: objStoreRegion  
    target:
      kind: Deployment
      name: ml-pipeline-ui
  - patch: |
      spec:
        template:
          spec:
            containers:
              - env:
                  - name: OBJECTSTORECONFIG_HOST
                    valueFrom:
                      configMapKeyRef:
                        name: pipeline-install-config
                        key: objStoreHost
                  - name: OBJECTSTORECONFIG_BUCKETNAME
                    valueFrom:
                      configMapKeyRef:
                        name: pipeline-install-config
                        key: bucketName
                  - name: OBJECTSTORECONFIG_REGION
                    valueFrom:
                      configMapKeyRef:
                        name: pipeline-install-config
                        key: objStoreRegion
                  - name: OBJECTSTORECONFIG_PORT
                    value: ""
                name: ml-pipeline-api-server
    target:
      kind: Deployment
      name: ml-pipeline
  interval: 6h
  timeout: 15m0s
  path: ./example
  prune: true
  sourceRef:
   kind: GitRepository
   name: kubeflow-instance
   namespace: ${releaseNamespace}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-tls
  namespace: istio-system
spec:
  commonName: istio-ingressgateway.istio-system.svc
  ipAddresses:
  # Replace var NODE_IP with the ip address of any cluster node or the LoadBalancer Service IP
  - 10.122.7.207
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  secretName: kubeflow-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-tls
  namespace: kubeflow
spec:
  commonName: istio-ingressgateway.istio-system.svc
  ipAddresses:
  # Replace var NODE_IP with the ip address of any cluster node or the LoadBalancer Service IP
  - 10.122.7.207
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  secretName: kubeflow-tls  
